services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: TFI
      MARIADB_USER: tfi
      MARIADB_PASSWORD: 1234
    networks:
      - tfi
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - tfi
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - tfi
    restart: always

volumes:
  mariadb:

networks:
  tfi:
    driver: bridge
