spring:
  application:
    name: inout

  datasource:
    url: jdbc:mariadb://localhost:27017/TFI
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

logging:
  level:
    root: INFO
    com.kevin.microservices: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: logs/backend.log
    max-size: 10MB
    max-history: 30